Torch issue716
OkuyanBoga/hc-qiskit-machine-learning pull request #18
Opened 2024-03-15 14:50 UTC by edoaltamura

### Summary
Merges fixes for issue 716 into main Dev.

✅ I have added the tests to cover my changes.
✅ I have updated the documentation accordingly.
✅ I have read the CONTRIBUTING document.

2024-03-18 10:36 UTC, OkuyanBoga requested changes

2024-03-18 10:36 UTC, OkuyanBoga commented on qiskit_machine_learning/connectors/torch_connector.py
> +    return signature
Is this covered by any unit tests?
- A test case for every `raise`
- Input/Output unit tests should be included

2024-03-18 10:36 UTC, OkuyanBoga commented on qiskit_machine_learning/connectors/torch_connector.py
> +def get_einsum_signature(n_dimensions: int, return_type: Literal["input", "weight"]) -> str:
Is this expected to be used by the users or is this an internal function?

2024-03-20 10:56 UTC, edoaltamura commented on qiskit_machine_learning/connectors/torch_connector.py
> +def get_einsum_signature(n_dimensions: int, return_type: Literal["input", "weight"]) -> str:
Just internal - would you recommend renaming to `_get_einsum_signature`?

2024-03-20 14:38 UTC, edoaltamura commented on qiskit_machine_learning/connectors/torch_connector.py
> +    return signature
Added in https://github.com/OkuyanBoga/hc-qiskit-machine-learning/pull/18/commits/034785b1d3ff525633329445249a56abf704a2f3.

2024-03-20 14:39 UTC, edoaltamura commented on qiskit_machine_learning/connectors/torch_connector.py
> +def get_einsum_signature(n_dimensions: int, return_type: Literal["input", "weight"]) -> str:
Renamed in https://github.com/OkuyanBoga/hc-qiskit-machine-learning/pull/18/commits/034785b1d3ff525633329445249a56abf704a2f3.

2024-03-20 14:41 UTC, edoaltamura reviewed
Fixed comments and ready for merge.

2024-04-03 15:27 UTC, OkuyanBoga approved these changes

2024-04-03 15:27 UTC, merged

2024-04-03 15:28 UTC, OkuyanBoga commented
You can submit PR to the main repository now.