Added support for EstimatorV2 primitives
OkuyanBoga/hc-qiskit-machine-learning pull request #48
Opened 2024-09-16 09:53 UTC by OkuyanBoga

Added support for V2 primitives for estimator_qnn and gradients. 

TO DO:

- [ ] Writing relative tests for V2.
- [ ]  Check spelling etc.

2024-09-16 10:14 UTC, OkuyanBoga reviewed
@edoaltamura @oscar-wallis please do corrections according to my reviews.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +from numpy import array
This is required to keep other functions the same, see line 138.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +            job = self._estimator.run(PUBs, precision=0.001, **options)
precision parameter might introduce issues for tests, we need to think about how to make stable tests for V2.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +                opt = options
self._get_local_options can be adapted but it is not a priority for now.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/gradients/spsa/spsa_estimator_gradient.py
> +# (C) Copyright IBM 2022, 2023.
Copy paste artifact, needs to be corrected.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/gradients/spsa/spsa_estimator_gradient.py
> +from numpy import array
This is required to keep other functions the same, see line 147.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/gradients/spsa/spsa_estimator_gradient.py
> +                opt = options
This can be written better by merging after result.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +            print('Warning: No number of qubits provided, using it from provided circuit, if the circuit is transpiled this can be wrong and cause issues.')
This is required since we might lose information about actual number of qubits of the circuit after the transpilation, not sure if it can simply be retrieved from transpiled_circuit.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +        return input_grad, weights_grad
Editing artefacts.

2024-09-16 10:14 UTC, OkuyanBoga commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +                job = self.gradient.run(circuits, observables, param_values, parameters=params)
Editing artefacts, need to add comments.

2024-09-27 10:42 UTC, edoaltamura requested changes

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +from qiskit_algorithms.gradients import (
```suggestion
from ..gradients import (
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +from qiskit_algorithms.gradients import (
Should we use relative imports for the derived primitives?

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +from qiskit_machine_learning.circuit.library import QNNCircuit
```suggestion
from ..circuit.library import QNNCircuit
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +from qiskit_machine_learning.exceptions import QiskitMachineLearningError
```suggestion
from ..exceptions import QiskitMachineLearningError
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +                :class:`~qiskit_algorithms.gradients.ParamShiftEstimatorGradient`, will be used.
```suggestion
                :class:`~qiskit_machine_learning.gradients.ParamShiftEstimatorGradient`, will be used.
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +        PUBs = [(job_circuits[i],[observable],job_param_values[i]) for i in range(n)]
```suggestion
        PUBs = [(job_circuits[i], [observable], job_param_values[i]) for i in range(n)]
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +        PUBs = [(job_circuits[i],[observable],job_param_values[i]) for i in range(n)]
I would also move `PUBs` inside the case
```python
elif isinstance(self._estimator, BaseEstimatorV2):
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +            job = self._estimator.run(PUBs, precision=0.001, **options)
Qiskit uses a default value of `0.0`: https://github.com/Qiskit/qiskit/blob/8ccbc8d28f34e3f2e1e0e8cbb66c4da95754b341/qiskit/primitives/statevector_estimator.py#L113
So to make tests reproducible we could fetch
```python
precision=self._default_precision
```
Since we are already within the `BaseEstimatorV2` case, we can assume that `_default_precision` is defined in the superclass.

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +            raise AlgorithmError("Wrong Estimator Type.")
```suggestion
            raise AlgorithmError(f"The accepted estimators are BaseEstimatorV1 (deprecated) and BaseEstimatorV2; got {type(self._estimator)} instead.")
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/gradients/param_shift/param_shift_estimator_gradient.py
> +            if isinstance(self._estimator, BaseEstimatorV2):
```suggestion
            elif isinstance(self._estimator, BaseEstimatorV2):
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/gradients/spsa/spsa_estimator_gradient.py
> +# (C) Copyright IBM 2022, 2023.
```suggestion
# (C) Copyright IBM 2022, 2024.
```

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +        return input_grad, weights_grad
```suggestion
        return input_grad, weights_grad
        
```
Adding a blank line at the end.

2024-09-27 10:42 UTC, edoaltamura commented on qiskit_machine_learning/neural_networks/estimator_qnn.py
> +            raise QiskitMachineLearningError("Wrong Estimator Type.")
```suggestion
            raise QiskitMachineLearningError(f"The accepted estimators are BaseEstimatorV1 (deprecated) and BaseEstimatorV2; got {type(self.estimator)} instead.")
```

Here we need to make sure we keep two things consistent:
- `self.estimator` (here) vs `self._estimator` (in other files)
- `QiskitMachineLearningError` (here) vs `AlgorithmsError` (other files) for the same error message. In this case, I would prefer going for the first, and gradually replace the `AlgorithmsError` calls.

2024-10-07 14:18 UTC, OkuyanBoga commented on test/neural_networks/test_estimator_qnn.py
>  CASE_DATA = {
@oscar-wallis Can you please copy paste this as CASE_DATA_V2 and adapt for V2?

2024-10-07 14:18 UTC, OkuyanBoga commented on test/neural_networks/test_estimator_qnn.py
> +        self.backend = GenericBackendV2(num_qubits=8)
Change this to num_qubits=3 or 4

2024-10-22 14:32 UTC, edoaltamura commented on test/neural_networks/test_estimator_qnn.py
> +        self.backend = GenericBackendV2(num_qubits=8)
Done

2024-10-22 15:15 UTC, edoaltamura commented on test/neural_networks/test_estimator_qnn.py
>  CASE_DATA = {
The shape itself is fixed, so closing this.

2024-10-23 12:49 UTC, edoaltamura commented
@OkuyanBoga all the shapes are fixed but the values are still a bit off. The circuit construction and options tests are working correctly, which suggests to me that the problem might lie in `forward` and `backward` Estimator passes. Since you edited that, could you please take a look at EstimatorQNN (V2 part)? Do you think this still has something to do with observables?

2024-10-31 15:39 UTC, OkuyanBoga commented
Despite suppressing the error rates, there are some issues with the following tests:
- Test parameter binding order gives result as expected
- Test Estimator QNN with input/output dimension 1/1.  [forward pass]
- Test Estimator QNN with input/output dimension 1/1. [backward pass with input gradients]
- Test Estimator QNN with input/output dimension 1/2.  [forward pass]
- Test Estimator QNN with input/output dimension 2/2. [forward pass]
- Test Estimator QNN properties and forward/backward pass for QNNCircuit construction [Test if backward pass yields equal results.]

2024-11-07 16:36 UTC, merged